# Generated by Django 6.0.5 on 2026-05-13 17:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_hash', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "Code d'accès",
                'verbose_name_plural': "Code d'accès",
            },
        ),
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('salaire_journalier', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'verbose_name': 'Employé',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('poids_gramme', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('prix_kg', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
            ],
            options={
                'verbose_name': 'Ingrédient',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='RecetteGateau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='gateaux/')),
                ('frais_emballage_unitaire', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('prix_vente_unitaire', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('nombre_unites_resultantes', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'verbose_name': 'Recette de gâteau',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='DetailJournee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('frais_local', models.DecimalField(decimal_places=2, default=350, max_digits=10)),
                ('frais_electricite_impots', models.DecimalField(decimal_places=2, default=150, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employes', models.ManyToManyField(blank=True, to='calculator.employe')),
            ],
            options={
                'verbose_name': 'Détail journée',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='RecetteIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_gramme', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.ingredient')),
                ('recette', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.recettegateau')),
            ],
            options={
                'verbose_name': 'Ingrédient de recette',
                'unique_together': {('recette', 'ingredient')},
            },
        ),
        migrations.AddField(
            model_name='recettegateau',
            name='ingredients',
            field=models.ManyToManyField(through='calculator.RecetteIngredient', to='calculator.ingredient'),
        ),
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_vendue', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('detail_journee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.detailjournee')),
                ('recette_gateau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.recettegateau')),
            ],
            options={
                'verbose_name': 'Vente',
                'unique_together': {('detail_journee', 'recette_gateau')},
            },
        ),
    ]
